const merge = require('object-funcs/merge')
const fn = require('../duration')
const test = require('tape')

const zero = { days: 0, hours: 0, minutes: 0, seconds: 0, milliseconds: 0 }

test('duration in milliseconds', function (t) {
  t.deepEqual(fn(0, 'ms'),        zero)
  t.deepEqual(fn(0.1, 'ms'),      zero)
  t.deepEqual(fn(0.01, 'ms'),     zero)
  t.deepEqual(fn(1),              merge(zero, { milliseconds: 1 }))
  t.deepEqual(fn(1, 'ms'),        merge(zero, { milliseconds: 1 }))
  t.deepEqual(fn(1.1, 'ms'),      merge(zero, { milliseconds: 1 }))
  t.deepEqual(fn(1.01, 'ms'),     merge(zero, { milliseconds: 1 }))
  t.deepEqual(fn(10, 'ms'),       merge(zero, { milliseconds: 10 }))
  t.deepEqual(fn(100, 'ms'),      merge(zero, { milliseconds: 100 }))
  t.deepEqual(fn(1000, 'ms'),     merge(zero, { seconds: 1 }))
  t.deepEqual(fn(1001, 'ms'),     merge(zero, { seconds: 1, milliseconds: 1 }))
  t.deepEqual(fn(1111, 'ms'),     merge(zero, { seconds: 1, milliseconds: 111 }))
  t.deepEqual(fn(59999.1, 'ms'),  merge(zero, { seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(59999, 'ms'),    merge(zero, { seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(60000.1, 'ms'),  merge(zero, { minutes: 1 }))
  t.deepEqual(fn(60000, 'ms'),    merge(zero, { minutes: 1 }))
  t.deepEqual(fn(3599999, 'ms'),  merge(zero, { minutes: 59, seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(3600000, 'ms'),  merge(zero, { hours: 1 }))
  t.deepEqual(fn(86399999, 'ms'), merge(zero, { hours: 23, minutes: 59, seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(86400000, 'ms'), merge(zero, { days: 1 }))
  t.deepEqual(fn(8639999999, 'ms'), merge(zero, { days: 99, hours: 23, minutes: 59, seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(8640000000, 'ms'), merge(zero, { days: 100 }))
  t.end()
})

test('duration in seconds', function (t) {
  t.deepEqual(fn(0, 's'),        zero)
  t.deepEqual(fn(0.0009, 's'),   merge(zero, { milliseconds: 1 }))
  t.deepEqual(fn(0.009, 's'),    merge(zero, { milliseconds: 9 }))
  t.deepEqual(fn(0.09, 's'),     merge(zero, { milliseconds: 90 }))
  t.deepEqual(fn(0.9, 's'),      merge(zero, { milliseconds: 900 }))
  t.deepEqual(fn(1, 's'),        merge(zero, { seconds: 1 }))
  t.deepEqual(fn(1.0001, 's'),   merge(zero, { seconds: 1 }))
  t.deepEqual(fn(1.000999, 's'), merge(zero, { seconds: 1, milliseconds: 1 }))
  t.deepEqual(fn(1.001, 's'),    merge(zero, { seconds: 1, milliseconds: 1 }))
  t.deepEqual(fn(1.01, 's'),     merge(zero, { seconds: 1, milliseconds: 10 }))
  t.deepEqual(fn(1.1, 's'),      merge(zero, { seconds: 1, milliseconds: 100 }))
  t.deepEqual(fn(59, 's'),       merge(zero, { seconds: 59 }))
  t.deepEqual(fn(59.009, 's'),   merge(zero, { seconds: 59, milliseconds: 9 }))
  t.deepEqual(fn(59.09, 's'),    merge(zero, { seconds: 59, milliseconds: 90 }))
  t.deepEqual(fn(59.9, 's'),     merge(zero, { seconds: 59, milliseconds: 900 }))
  t.deepEqual(fn(60, 's'),       merge(zero, { minutes: 1 }))
  t.deepEqual(fn(60.0001, 's'),  merge(zero, { minutes: 1 }))
  t.deepEqual(fn(60.001, 's'),   merge(zero, { minutes: 1, milliseconds: 1 }))
  t.deepEqual(fn(60.01, 's'),    merge(zero, { minutes: 1, milliseconds: 10 }))
  t.deepEqual(fn(60.1, 's'),     merge(zero, { minutes: 1, milliseconds: 100 }))
  t.deepEqual(fn(61.1, 's'),     merge(zero, { minutes: 1, seconds: 1, milliseconds: 100 }))
  t.deepEqual(fn(61.1, 's'),     merge(zero, { minutes: 1, seconds: 1, milliseconds: 100 }))
  t.deepEqual(fn(3599, 's'),     merge(zero, { minutes: 59, seconds: 59 }))
  t.deepEqual(fn(3600, 's'),     merge(zero, { hours: 1 }))
  t.deepEqual(fn(86399, 's'),    merge(zero, { hours: 23, minutes: 59, seconds: 59 }))
  t.deepEqual(fn(86400, 's'),    merge(zero, { days: 1 }))
  t.deepEqual(fn(8639999, 's'),  merge(zero, { days: 99, hours: 23, minutes: 59, seconds: 59 }))
  t.deepEqual(fn(8640000, 's'),  merge(zero, { days: 100 }))
  t.end()
})

test('duration in minutes', function (t) {
  t.deepEqual(fn(0, 'm'),         zero)
  t.deepEqual(fn(0.1, 'm'),       merge(zero, { seconds: 6 }))
  t.deepEqual(fn(0.01, 'm'),      merge(zero, { seconds: 0, milliseconds: 600 }))
  t.deepEqual(fn(0.001, 'm'),     merge(zero, { seconds: 0, milliseconds: 60 }))
  t.deepEqual(fn(0.999, 'm'),     merge(zero, { seconds: 59, milliseconds: 940 }))
  t.deepEqual(fn(0.9999, 'm'),    merge(zero, { seconds: 59, milliseconds: 994 }))
  t.deepEqual(fn(0.99999, 'm'),   merge(zero, { seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(0.99999, 'm'),   merge(zero, { seconds: 59, milliseconds: 999 }))
  t.deepEqual(fn(1.1, 'm'),       merge(zero, { minutes: 1, seconds: 6 }))
  t.deepEqual(fn(1.01, 'm'),      merge(zero, { minutes: 1, milliseconds: 600 }))
  t.deepEqual(fn(1.001, 'm'),     merge(zero, { minutes: 1, milliseconds: 60 }))
  t.deepEqual(fn(59.9, 'm'),      merge(zero, { minutes: 59, seconds: 54 }))
  t.deepEqual(fn(59.99, 'm'),     merge(zero, { minutes: 59, seconds: 59, milliseconds: 400 }))
  t.deepEqual(fn(59.999, 'm'),    merge(zero, { minutes: 59, seconds: 59, milliseconds: 940 }))
  t.deepEqual(fn(59.9999, 'm'),   merge(zero, { minutes: 59, seconds: 59, milliseconds: 994 }))
  t.deepEqual(fn(60, 'm'),        merge(zero, { hours: 1 }))
  t.deepEqual(fn(1439, 'm'),      merge(zero, { hours: 23, minutes: 59 }))
  t.deepEqual(fn(1439.9, 'm'),    merge(zero, { hours: 23, minutes: 59, seconds: 54 }))
  t.deepEqual(fn(1439.99, 'm'),   merge(zero, { hours: 23, minutes: 59, seconds: 59, milliseconds: 400 }))
  t.deepEqual(fn(1439.999, 'm'),  merge(zero, { hours: 23, minutes: 59, seconds: 59, milliseconds: 940 }))
  t.deepEqual(fn(1439.9999, 'm'), merge(zero, { hours: 23, minutes: 59, seconds: 59, milliseconds: 994 }))
  t.deepEqual(fn(1440, 'm'),      merge(zero, { days: 1 }))
  t.deepEqual(fn(143999, 'm'),    merge(zero, { days: 99, hours: 23, minutes: 59 }))
  t.deepEqual(fn(144000, 'm'),    merge(zero, { days: 100 }))
  t.end()
})

test('duration in hours', function (t) {
  t.deepEqual(fn(0, 'h'),        zero)
  t.deepEqual(fn(0.1, 'h'),      merge(zero, { minutes: 6 }))
  t.deepEqual(fn(0.01, 'h'),     merge(zero, { seconds: 36 }))
  t.deepEqual(fn(0.001, 'h'),    merge(zero, { seconds: 3, milliseconds: 600 }))
  t.deepEqual(fn(0.0001, 'h'),   merge(zero, { milliseconds: 360 }))
  t.deepEqual(fn(0.9, 'h'),      merge(zero, { minutes: 54 }))
  t.deepEqual(fn(0.99, 'h'),     merge(zero, { minutes: 59, seconds: 24 }))
  t.deepEqual(fn(0.999, 'h'),    merge(zero, { minutes: 59, seconds: 56, milliseconds: 400 }))
  t.deepEqual(fn(0.9999, 'h'),   merge(zero, { minutes: 59, seconds: 59, milliseconds: 640 }))
  t.deepEqual(fn(1, 'h'),        merge(zero, { hours: 1 }))
  t.deepEqual(fn(1.1, 'h'),      merge(zero, { hours: 1, minutes: 6 }))
  t.deepEqual(fn(1.01, 'h'),     merge(zero, { hours: 1, seconds: 36 }))
  t.deepEqual(fn(1.001, 'h'),    merge(zero, { hours: 1, seconds: 3, milliseconds:600 }))
  t.deepEqual(fn(1.001, 'h'),    merge(zero, { hours: 1, seconds: 3, milliseconds:600 }))
  t.deepEqual(fn(24, 'h'),       merge(zero, { days: 1 }))
  t.deepEqual(fn(23.99999, 'h'), merge(zero, { hours: 23, minutes: 59, seconds: 59, milliseconds:964 }))
  t.end()
})

test('duration in days', function (t) {
  t.deepEqual(fn(0, 'd'),        zero)
  t.deepEqual(fn(0.1, 'd'),      merge(zero, { hours: 2, minutes: 24 }))
  t.deepEqual(fn(0.01, 'd'),     merge(zero, { minutes: 14, seconds: 24 }))
  t.deepEqual(fn(0.001, 'd'),    merge(zero, { minutes: 1, seconds: 26, milliseconds: 400 }))
  t.deepEqual(fn(0.0001, 'd'),   merge(zero, { seconds: 8, milliseconds: 640 }))
  t.deepEqual(fn(99.9, 'd'),     merge(zero, { days: 99, hours: 21, minutes: 36 }))
  t.deepEqual(fn(99.99, 'd'),    merge(zero, { days: 99, hours: 23, minutes: 45, seconds: 36 }))
  t.deepEqual(fn(99.999, 'd'),   merge(zero, { days: 99, hours: 23, minutes: 58, seconds: 33, milliseconds: 600 }))
  t.deepEqual(fn(99.9999, 'd'),  merge(zero, { days: 99, hours: 23, minutes: 59, seconds: 51, milliseconds: 360 }))
  t.deepEqual(fn(99.99999, 'd'), merge(zero, { days: 99, hours: 23, minutes: 59, seconds: 59, milliseconds: 136 }))
  t.deepEqual(fn(100, 'd'),      merge(zero, { days: 100 }))
  t.end()
})

test('duration wrong values', function (t) {
  t.equal(fn('0', 'd'),       undefined)
  t.equal(fn(-1, 'd'),        undefined)
  t.equal(fn(-0.1, 'd'),      undefined)
  t.equal(fn({}, 'd'),        undefined)
  t.equal(fn(/./, 'd'),       undefined)
  t.equal(fn(true, 'd'),      undefined)
  t.equal(fn(false, 'd'),     undefined)
  t.equal(fn(null, 'd'),      undefined)
  t.equal(fn(undefined, 'd'), undefined)
  t.equal(fn(NaN, 'd'),       undefined)
  t.end()
})
